import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import WarningSuppressor from "@/components/WarningSuppressor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Expense Tracker",
  description: "Generated by create next app",
  icons: {
    icon: './favicon.svg',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      >
        <main className="min-h-screen p-4 md:p-8">
          <WarningSuppressor>{children}</WarningSuppressor>
        </main>
      </body>
    </html>
  );
}
